### PR TITLE
revise package objects (WIP)

### PR DESCRIPTION
**Pull request by jakob-r**

### CODE REVIEW

**Comment by jakob-r** [comment]
Should we use R6?

**Comment by surmann** [comment]
Does it make things easier? Do we have to update the whole package?

**Comment by jakob-r** [comment]
It makes things less messy inside. From outside nothing has to change.

**Comment by jakob-r** [comment]
Done, please review @mllg 
Note: I simplified the objects to contain the bare minimum to run well with remotes

**Pull request merged**
